In [ ]:
!pip install pyentrp

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 39.6 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.25.2
    Uninstalling numpy-1.25.2:
      Successfully uninstalled numpy-1.25.2


In [ ]:
import os
import pyentrp as pyen
import pandas as pd
import numpy as np
import scipy.stats as stats

In [ ]:
!pip show pyentrp

Name: pyentrp
Version: 0.9.0
Summary: A Python library for computing entropy measures for time series analysis.
Home-page: 
Author: Nikolay Donets
Author-email: nd@donets.org
License: Apache-2.0
Location: /usr/local/lib/python3.10/dist-packages
Requires: numpy
Required-by: 


# Load amateur GSR

In [ ]:
os.chdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/eSports_Sensors_Dataset-master/HRV csvs/HRV_GSR_Final/GSR/amateurs/match_13')
files = os.listdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/eSports_Sensors_Dataset-master/HRV csvs/HRV_GSR_Final/GSR/amateurs/match_13')
am_gsr_data = dict()
for f in files:
  if 'csv' in f:
    #print()
    f_name = f.split('.')[0]
    print(f'Am_{f_name}')
    am_gsr_data[f_name] = pd.read_csv(f)

Am_player_0
Am_player_1
Am_player_2
Am_player_3
Am_player_4


# Load amateur HRV data


In [ ]:
os.chdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/eSports_Sensors_Dataset-master/HRV csvs/HRV_GSR_Final/HRV/amateurs/match_13')
files = os.listdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/eSports_Sensors_Dataset-master/HRV csvs/HRV_GSR_Final/HRV/amateurs/match_13')
am_hrv_data = dict()
for f in files:
  if 'csv' in f:
    #print()
    f_name = f.split('.')[0]
    print(f'Am_{f_name}')
    am_hrv_data[f_name] = pd.read_csv(f)

Am_match_13_player_0
Am_match_13_player_1
Am_match_13_player_2
Am_match_13_player_3
Am_match_13_player_4


# Load Pro GSR data

In [ ]:
os.chdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/eSports_Sensors_Dataset-master/HRV csvs/HRV_GSR_Final/GSR/pros/match_10')
files = os.listdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/eSports_Sensors_Dataset-master/HRV csvs/HRV_GSR_Final/GSR/pros/match_10')
pro_gsr_data = dict()
for f in files:
  if 'csv' in f:
    #print()
    f_name = f.split('.')[0]
    print(f'Am_{f_name}')
    pro_gsr_data[f_name] = pd.read_csv(f)

Am_player_0
Am_player_1
Am_player_2
Am_player_3
Am_player_4


# Load pro HRV Data

In [ ]:
os.chdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/eSports_Sensors_Dataset-master/HRV csvs/HRV_GSR_Final/HRV/pros/match_10')
files = os.listdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/eSports_Sensors_Dataset-master/HRV csvs/HRV_GSR_Final/HRV/pros/match_10')
pro_hrv_data = dict()
for f in files:
  if 'csv' in f:
    #print()
    f_name = f.split('.')[0]
    print(f'Am_{f_name}')
    pro_hrv_data[f_name] = pd.read_csv(f)

Am_match_10_player_0
Am_match_10_player_1
Am_match_10_player_2
Am_match_10_player_3
Am_match_10_player_4


# Load surrogate data

In [ ]:
# load 100 pro surrogates gsr
pro_100_gsr = os.listdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/Python code/individual analysis/pro_surrogates/GSR')[:100]

In [ ]:
pro_100_surr_gsr = [pd.read_csv(f'/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/Python code/individual analysis/pro_surrogates/GSR/{f}') for f in pro_100_gsr]

In [ ]:
# load 100 pro surrogate hrv
pro_100_hrv = os.listdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/Python code/individual analysis/pro_surrogates/HRV')[:100]
pro_100_surr_hrv = [pd.read_csv(f'/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/Python code/individual analysis/pro_surrogates/HRV/{f}') for f in pro_100_hrv]

In [ ]:
# load 100 amateur surrogate gsr
am_100_gsr = os.listdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/Python code/individual analysis/amateur_surrogates/GSR')[:100]
am_100_surr_gsr = [pd.read_csv(f'/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/Python code/individual analysis/amateur_surrogates/GSR/{f}') for f in am_100_gsr]

In [ ]:
# load 1000 amateur surrogate hrv
am_100_hrv = os.listdir('/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/Python code/individual analysis/amateur_surrogates/HRV')[:100]
am_100_surr_hrv = [pd.read_csv(f'/content/drive/MyDrive/Tilburg/Masters CSAI/Year 1 - Semester 2/Complex Systems/CS Project/Python code/individual analysis/amateur_surrogates/HRV/{f}') for f in am_100_hrv]

# Calculate sample entropy

In [ ]:
pro_player_data = {'GSR' : pro_gsr_data,'HRV' : pro_hrv_data}
am_player_data = {'GSR' : am_gsr_data, 'HRV':  am_hrv_data}

In [ ]:
from pyentrp import entropy

## Professionals

In [ ]:
pro_gsr_sampen = []
for player in pro_player_data['GSR']:
  print(player)
  vals = pro_player_data['GSR'][player]['gsr'].values
  std_ts = np.std(vals)
  mean_ts = np.mean(vals)
  vals_stationary = (vals - mean_ts)/std_ts
  sampen = entropy.sample_entropy(vals_stationary,sample_length = 2, tolerance = 0.15 * np.std(vals_stationary))
  pro_gsr_sampen.append((player,sampen[0]))
  # for player in pro_player_data[d]:
  #   print(d, player)
  #   vals = pro_player_data[d][player]['gsr'].values
  #   std_ts = np.std(vals)
  #   sampen = entropy.sample_entropy(vals,sample_length = 2, tolerance = 0.15 * std_ts)
  #   pro_gsr_sampen.append(player,sampen)

player_0
player_1
player_2
player_3
player_4


In [ ]:
pro_gsr_sampen

[('player_0', 2.50821064640672),
 ('player_1', 1.5567081898591233),
 ('player_2', 2.397020169949923),
 ('player_3', 2.3835515217375143),
 ('player_4', 2.322200057617593)]

In [ ]:
pro_hrv_sampen = []
for player in pro_player_data['HRV']:
  print(player)
  vals = pro_player_data['HRV'][player]['RMSSD'].values
  std_ts = np.std(vals)
  mean_ts = np.mean(vals)
  vals_stationary = (vals - mean_ts) / std_ts
  sampen = entropy.sample_entropy(vals_stationary,sample_length = 2, tolerance = 0.15 * np.std(vals_stationary))
  pro_hrv_sampen.append((player,sampen[0]))
  # for player in pro_player_data[d]:
  #   print(d, player)
  #   vals = pro_player_data[d][player]['gsr'].values
  #   std_ts = np.std(vals)
  #   sampen = entropy.sample_entropy(vals,sample_length = 2, tolerance = 0.15 * std_ts)
  #   pro_gsr_sampen.append(player,sampen)

match_10_player_0
match_10_player_1
match_10_player_2
match_10_player_3
match_10_player_4


In [ ]:
pro_hrv_sampen

[('match_10_player_0', 2.543312272656874),
 ('match_10_player_1', 2.500752658238078),
 ('match_10_player_2', 2.5520459526256287),
 ('match_10_player_3', 2.4207099505645417),
 ('match_10_player_4', 2.4924538554233835)]

## Amateurs

In [ ]:
am_gsr_sampen = []
for player in am_player_data['GSR']:
  print(player)
  vals = am_player_data['GSR'][player]['gsr'].values
  std_ts = np.std(vals)
  mean_ts = np.mean(vals)
  vals_stationary = (vals - mean_ts) / std_ts
  sampen = entropy.sample_entropy(vals_stationary,sample_length = 2, tolerance = 0.15 * np.std(vals_stationary))
  am_gsr_sampen.append((player,sampen[0]))
  # for player in pro_player_data[d]:
  #   print(d, player)
  #   vals = pro_player_data[d][player]['gsr'].values
  #   std_ts = np.std(vals)
  #   sampen = entropy.sample_entropy(vals,sample_length = 2, tolerance = 0.15 * std_ts)
  #   pro_gsr_sampen.append(player,sampen)

player_0
player_1
player_2
player_3
player_4


In [ ]:
am_gsr_sampen

[('player_0', 2.3315838018763273),
 ('player_1', 2.4140639460840996),
 ('player_2', 2.475087708219005),
 ('player_3', 2.421365722317657),
 ('player_4', 2.4814651312473797)]

In [ ]:
am_hrv_sampen = []
for player in am_player_data['HRV']:
  print(player)
  vals = am_player_data['HRV'][player]['RMSSD'].values
  std_ts = np.std(vals)
  mean_ts = np.mean(vals)
  vals_stationary = (vals - mean_ts) / std_ts
  sampen = entropy.sample_entropy(vals_stationary,sample_length = 2, tolerance = 0.15 * np.std(vals_stationary))
  am_hrv_sampen.append((player,sampen[0]))
  # for player in pro_player_data[d]:
  #   print(d, player)
  #   vals = pro_player_data[d][player]['gsr'].values
  #   std_ts = np.std(vals)
  #   sampen = entropy.sample_entropy(vals,sample_length = 2, tolerance = 0.15 * std_ts)
  #   pro_gsr_sampen.append(player,sampen)

match_13_player_0
match_13_player_1
match_13_player_2
match_13_player_3
match_13_player_4


In [ ]:
am_hrv_sampen

[('match_13_player_0', 2.468323998363695),
 ('match_13_player_1', 2.456473958446199),
 ('match_13_player_2', 2.460408389751034),
 ('match_13_player_3', 2.535426510119478),
 ('match_13_player_4', 2.368808345253973)]

# Surrogate sample entropy

## Professionals

In [ ]:
p0_sur_gsr_ens = []
p1_sur_gsr_ens = []
p2_sur_gsr_ens = []
p3_sur_gsr_ens = []
p4_sur_gsr_ens = []
for m in pro_100_surr_gsr:
  p0 = m['player_0'].values
  p1 = m['player_1'].values
  p2 = m['player_2'].values
  p3 = m['player_3'].values
  p4 = m['player_4'].values

  p0_stationary = (p0 - np.mean(p0))/np.std(p0)
  p1_stationary = (p1 - np.mean(p1))/np.std(p1)
  p2_stationary = (p2 - np.mean(p2))/np.std(p2)
  p3_stationary = (p3 - np.mean(p3))/np.std(p3)
  p4_stationary = (p4 - np.mean(p4))/np.std(p4)

  p0_sampen = entropy.sample_entropy(p0_stationary,sample_length = 2, tolerance = 0.15 * np.std(p0_stationary))[0]
  p1_sampen = entropy.sample_entropy(p1_stationary,sample_length = 2, tolerance = 0.15 * np.std(p1_stationary))[0]
  p2_sampen = entropy.sample_entropy(p2_stationary,sample_length = 2, tolerance = 0.15 * np.std(p2_stationary))[0]
  p3_sampen = entropy.sample_entropy(p3_stationary,sample_length = 2, tolerance = 0.15 * np.std(p3_stationary))[0]
  p4_sampen = entropy.sample_entropy(p4_stationary,sample_length = 2, tolerance = 0.15 * np.std(p4_stationary))[0]

  p0_sur_gsr_ens.append(p0_sampen)
  p1_sur_gsr_ens.append(p1_sampen)
  p2_sur_gsr_ens.append(p2_sampen)
  p3_sur_gsr_ens.append(p3_sampen)
  p4_sur_gsr_ens.append(p4_sampen)


In [ ]:
p0_sur_hrv_ens = []
p1_sur_hrv_ens = []
p2_sur_hrv_ens = []
p3_sur_hrv_ens = []
p4_sur_hrv_ens = []
for m in pro_100_surr_hrv:
  p0 = m['player_0'].values
  p1 = m['player_1'].values
  p2 = m['player_2'].values
  p3 = m['player_3'].values
  p4 = m['player_4'].values

  p0_stationary = (p0 - np.mean(p0))/np.std(p0)
  p1_stationary = (p1 - np.mean(p1))/np.std(p1)
  p2_stationary = (p2 - np.mean(p2))/np.std(p2)
  p3_stationary = (p3 - np.mean(p3))/np.std(p3)
  p4_stationary = (p4 - np.mean(p4))/np.std(p4)

  p0_sampen = entropy.sample_entropy(p0_stationary,sample_length = 2, tolerance = 0.15 * np.std(p0_stationary))[0]
  p1_sampen = entropy.sample_entropy(p1_stationary,sample_length = 2, tolerance = 0.15 * np.std(p1_stationary))[0]
  p2_sampen = entropy.sample_entropy(p2_stationary,sample_length = 2, tolerance = 0.15 * np.std(p2_stationary))[0]
  p3_sampen = entropy.sample_entropy(p3_stationary,sample_length = 2, tolerance = 0.15 * np.std(p3_stationary))[0]
  p4_sampen = entropy.sample_entropy(p4_stationary,sample_length = 2, tolerance = 0.15 * np.std(p4_stationary))[0]

  p0_sur_hrv_ens.append(p0_sampen)
  p1_sur_hrv_ens.append(p1_sampen)
  p2_sur_hrv_ens.append(p2_sampen)
  p3_sur_hrv_ens.append(p3_sampen)
  p4_sur_hrv_ens.append(p4_sampen)

## Amateurs

In [ ]:
am_p0_sur_gsr_ens = []
am_p1_sur_gsr_ens = []
am_p2_sur_gsr_ens = []
am_p3_sur_gsr_ens = []
am_p4_sur_gsr_ens = []
for m in am_100_surr_gsr:
  p0 = m['player_0'].values
  p1 = m['player_1'].values
  p2 = m['player_2'].values
  p3 = m['player_3'].values
  p4 = m['player_4'].values

  p0_stationary = (p0 - np.mean(p0))/np.std(p0)
  p1_stationary = (p1 - np.mean(p1))/np.std(p1)
  p2_stationary = (p2 - np.mean(p2))/np.std(p2)
  p3_stationary = (p3 - np.mean(p3))/np.std(p3)
  p4_stationary = (p4 - np.mean(p4))/np.std(p4)

  p0_sampen = entropy.sample_entropy(p0_stationary,sample_length = 2, tolerance = 0.15 * np.std(p0_stationary))[0]
  p1_sampen = entropy.sample_entropy(p1_stationary,sample_length = 2, tolerance = 0.15 * np.std(p1_stationary))[0]
  p2_sampen = entropy.sample_entropy(p2_stationary,sample_length = 2, tolerance = 0.15 * np.std(p2_stationary))[0]
  p3_sampen = entropy.sample_entropy(p3_stationary,sample_length = 2, tolerance = 0.15 * np.std(p3_stationary))[0]
  p4_sampen = entropy.sample_entropy(p4_stationary,sample_length = 2, tolerance = 0.15 * np.std(p4_stationary))[0]

  am_p0_sur_gsr_ens.append(p0_sampen)
  am_p1_sur_gsr_ens.append(p1_sampen)
  am_p2_sur_gsr_ens.append(p2_sampen)
  am_p3_sur_gsr_ens.append(p3_sampen)
  am_p4_sur_gsr_ens.append(p4_sampen)

In [ ]:
am_p0_sur_hrv_ens = []
am_p1_sur_hrv_ens = []
am_p2_sur_hrv_ens = []
am_p3_sur_hrv_ens = []
am_p4_sur_hrv_ens = []

for m in am_100_surr_hrv:
  p0 = m['player_0'].values
  p1 = m['player_1'].values
  p2 = m['player_2'].values
  p3 = m['player_3'].values
  p4 = m['player_4'].values

  p0_stationary = (p0 - np.mean(p0))/np.std(p0)
  p1_stationary = (p1 - np.mean(p1))/np.std(p1)
  p2_stationary = (p2 - np.mean(p2))/np.std(p2)
  p3_stationary = (p3 - np.mean(p3))/np.std(p3)
  p4_stationary = (p4 - np.mean(p4))/np.std(p4)

  p0_sampen = entropy.sample_entropy(p0_stationary,sample_length = 2, tolerance = 0.15 * np.std(p0_stationary))[0]
  p1_sampen = entropy.sample_entropy(p1_stationary,sample_length = 2, tolerance = 0.15 * np.std(p1_stationary))[0]
  p2_sampen = entropy.sample_entropy(p2_stationary,sample_length = 2, tolerance = 0.15 * np.std(p2_stationary))[0]
  p3_sampen = entropy.sample_entropy(p3_stationary,sample_length = 2, tolerance = 0.15 * np.std(p3_stationary))[0]
  p4_sampen = entropy.sample_entropy(p4_stationary,sample_length = 2, tolerance = 0.15 * np.std(p4_stationary))[0]

  am_p0_sur_hrv_ens.append(p0_sampen)
  am_p1_sur_hrv_ens.append(p1_sampen)
  am_p2_sur_hrv_ens.append(p2_sampen)
  am_p3_sur_hrv_ens.append(p3_sampen)
  am_p4_sur_hrv_ens.append(p4_sampen)


# Condifence intervals

In [ ]:
players = ['player_0',
           'player_1',
           'player_2',
           'player_3',
           'player_4',]

## Professionals

In [ ]:
pro_stats_gsr = {}
pro_gsr_ens = [p0_sur_gsr_ens,
           p1_sur_gsr_ens,
           p2_sur_gsr_ens,
           p3_sur_gsr_ens,
           p4_sur_gsr_ens,]
for i,p in enumerate(pro_gsr_ens):
  #print(len(p))
  mean = np.mean(p)
  sd = np.std(p)
  err = stats.t.ppf(0.975, df = len(p) -1) / np.sqrt(len(p))
  ci = [mean-err, mean, mean + err]
  print(np.round(ci,3))
  pro_stats_gsr[players[i]] = (np.round(ci,3))


[2.309 2.508 2.706]
[1.36  1.558 1.757]
[2.199 2.398 2.596]
[2.184 2.383 2.581]
[2.124 2.323 2.521]


In [ ]:
pro_gsr_sampen

[('player_0', 2.50821064640672),
 ('player_1', 1.5567081898591233),
 ('player_2', 2.397020169949923),
 ('player_3', 2.3835515217375143),
 ('player_4', 2.322200057617593)]

In [ ]:
pro_stats_hrv = {}
pro_hrv_ens = [p0_sur_hrv_ens,
           p1_sur_hrv_ens,
           p2_sur_hrv_ens,
           p3_sur_hrv_ens,
           p4_sur_hrv_ens,]
for i,p in enumerate(pro_hrv_ens):
  #print(len(p))
  mean = np.mean(p)
  sd = np.std(p)
  err = stats.t.ppf(0.975, df = len(p) -1) / np.sqrt(len(p))
  ci = [mean-err,mean, mean + err]
  print(np.round(ci,3))
  pro_stats_hrv[players[i]] = (np.round(ci,3))


[2.336 2.535 2.733]
[2.288 2.486 2.685]
[2.359 2.558 2.756]
[2.234 2.433 2.631]
[2.316 2.515 2.713]


In [ ]:
pro_hrv_sampen

[('match_10_player_0', 2.543312272656874),
 ('match_10_player_1', 2.500752658238078),
 ('match_10_player_2', 2.5520459526256287),
 ('match_10_player_3', 2.4207099505645417),
 ('match_10_player_4', 2.4924538554233835)]

## Amateurs

In [ ]:
am_stats_gsr = {}
am_gsr_ens = [am_p0_sur_gsr_ens,
           am_p1_sur_gsr_ens,
           am_p2_sur_gsr_ens,
           am_p3_sur_gsr_ens,
           am_p4_sur_gsr_ens,]
for i,p in enumerate(am_gsr_ens):
  #print(len(p))
  mean = np.mean(p)
  sd = np.std(p)
  err = stats.t.ppf(0.975, df = len(p) -1) / np.sqrt(len(p))
  ci = [mean-err, mean, mean + err]
  print(np.round(ci,3))
  am_stats_gsr[players[i]] = (np.round(ci,3))


[2.134 2.332 2.531]
[2.216 2.415 2.613]
[2.277 2.476 2.674]
[2.224 2.422 2.621]
[2.283 2.481 2.68 ]


In [ ]:
am_gsr_sampen

[('player_0', 2.3315838018763273),
 ('player_1', 2.4140639460840996),
 ('player_2', 2.475087708219005),
 ('player_3', 2.421365722317657),
 ('player_4', 2.4814651312473797)]

In [ ]:
am_stats_hrv = {}
am_hrv_ens = [am_p0_sur_hrv_ens,
           am_p1_sur_hrv_ens,
           am_p2_sur_hrv_ens,
           am_p3_sur_hrv_ens,
           am_p4_sur_hrv_ens,]
for i,p in enumerate(am_hrv_ens):
  #print(len(p))
  mean = np.mean(p)
  sd = np.std(p)
  err = stats.t.ppf(0.975, df = len(p) -1) / np.sqrt(len(p))
  ci = [mean-err, mean, mean + err]
  print(np.round(ci,3))
  am_stats_hrv[players[i]] = (np.round(ci,3))


[2.261 2.46  2.658]
[2.257 2.456 2.654]
[2.269 2.468 2.666]
[2.342 2.54  2.739]
[2.171 2.37  2.568]


In [ ]:
am_hrv_sampen

[('match_13_player_0', 2.468323998363695),
 ('match_13_player_1', 2.456473958446199),
 ('match_13_player_2', 2.460408389751034),
 ('match_13_player_3', 2.535426510119478),
 ('match_13_player_4', 2.368808345253973)]